### ISSUE TITLE
[Bug]: Snaphu crashing with parallelization options

### ISSUE THREAD

**Issue by sssangha** [isce-framework/snaphu-py#46]
I was testing out the parallelization options through dolphin, where I specified `n_parallel_jobs = 2` and `n_parallel_tiles = (2,2)`, half of the pairs are processed before I encounter this error:
```
snaphu v2.0.6
14 parameters input from file /u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/snaphu-regrow-conncomps.config.3azoqy6v.txt (14 lines total)
Reading unwrapped phase from file /u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/snaphu.unw.kmu6glh6.f4
Reading interferogram magnitude from file /u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/snaphu.mag.852wqywg.f4
Reading byte mask from file /u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/snaphu.mask.1c69a87q.u1
No weight file specified.  Assuming uniform weights
Reading correlation data from file /u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/snaphu.corr.j52o8wvj.f4
Calculating smooth-solution cost parameters
Growing connected component mask
Writing connected components to file /u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/snaphu.conncomp.8t07h1t7.u4 as 4-byte unsigned ints
Program snaphu done
Elapsed processor time:   0:00:08.00
Elapsed wall clock time:  0:00:09
Assembling tiles
Traceback (most recent call last):
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/snaphu/_snaphu.py", line 89, in run_snaphu
    subprocess.run(args, stderr=subprocess.PIPE, check=True, text=True)
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/snaphu/snaphu', '-f', '/u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/snaphu.config.hvxqxzjp.txt']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/trappist-r0/ssangha/DISP_work/Hawaii/test_packages/calval-DISP/dolphin_PSTworkflow/pst_dolphin_workflow.py", line 368, in <module>
    access_cslcs(inp)
  File "/u/trappist-r0/ssangha/DISP_work/Hawaii/test_packages/calval-DISP/dolphin_PSTworkflow/pst_dolphin_workflow.py", line 355, in access_cslcs
    unwrapping.run(
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/dolphin/_log.py", line 118, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/dolphin/workflows/unwrapping.py", line 75, in run
    unwrapped_paths, conncomp_paths = unwrap.run(
                                      ^^^^^^^^^^^
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/dolphin/_log.py", line 118, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/dolphin/unwrap/_unwrap.py", line 154, in run
    _unw_path, _cc_path = fut.result()
                          ^^^^^^^^^^^^
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/dolphin/unwrap/_unwrap.py", line 244, in unwrap
    return unwrap_snaphu_py(
           ^^^^^^^^^^^^^^^^^
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/dolphin/unwrap/_snaphu_py.py", line 108, in unwrap_snaphu_py
    snaphu.unwrap(
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/snaphu/_unwrap.py", line 603, in unwrap
    run_snaphu(config_file)
  File "/u/trappist-r0/ssangha/conda_installation/stable_mach14_2022/envs/dolphin-env/lib/python3.11/site-packages/snaphu/_snaphu.py", line 92, in run_snaphu
    raise RuntimeError(errmsg) from e
RuntimeError: WARNING: Tile overlap is small (may give bad results)
Can't open file /u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/snaphu_tiles_10495/tmptile_snaphu.unw.ag1dtgj7.f4_0_0.3366_regions
Abort
```

I should mention I was able to run through just fine with `n_parallel_jobs = 1` and `n_parallel_tiles = (1,1)`

Please advise on how I may be able to facilitate debugging actions here. Many thanks!

Relevant environment versioning details:
snaphu = 0.2.0
dolphin commit hash = 071917c1651adba34593a4bd9647543a7f5af913

**Comment by gmgunter** [comment]
Thanks for the report, @sssangha.

When you run dolphin with `n_parallel_jobs = 2`, it launches two separate processes that each run `snaphu.unwrap()` on a different interferogram. Based on the console output that you posted, it looks like the first process completed successfully but the second one failed. It also appears that both jobs are using the same scratch directory:

```
/u/trappist-r0/ssangha/DISP_work/Hawaii/dolphin/test3_phass_hawaii_des/dolphin_output/stitched_interferograms/scratch/
```

By default, `snaphu.unwrap()` deletes its scratch directory when it finishes processing. (This can be overridden by passing [`delete_scratch=False`](https://github.com/isce-framework/snaphu-py/blob/ab58773ea3cb623f5c67ed4699fcfb1a7f426865/src/snaphu/_unwrap.py#L468-L471).)

So I think what's happening here is that, when `n_parallel_jobs` is >1, dolphin is launching multiple jobs that all run `snaphu.unwrap()` with the same scratch directory. Once the first job completes, it deletes the scratch directory, causing any remaining in-progress jobs to fail once they try to read from or write to that directory.

If we add `delete_scratch=False` to the [call to `snaphu.unwrap()`](https://github.com/isce-framework/dolphin/blob/071917c1651adba34593a4bd9647543a7f5af913/src/dolphin/unwrap/_snaphu_py.py#L108-L129) in dolphin, then it should be safe to run multiple snaphu-py jobs with the same scratch directory, because we're careful to ensure that all intermediate files don't have name collisions with other processes.

A better approach might be to modify snaphu-py to preserve the scratch directory itself and only delete its contents that were created by the current snaphu-py process. That should allow us to run multiple jobs with the same scratch directory safely while still cleaning up after ourselves.

WDYT, @scottstanie?

**Comment by scottstanie** [comment]
Thanks for figuring that out Geoff! What do you think of altering it to check if the directory exists, like here:
 https://github.com/opera-adt/opera-utils/blob/66ce141b9d02ada50315bb58d43531e9102f0019/src/opera_utils/_utils.py#L159-L160

`dolphin` is making the scratch directory in advance right now, so it would not be deleted with the extra `already_exists` check

**Comment by gmgunter** [comment]
:+1: Sounds good to me. That should be pretty easily to implement.
